#!/usr/bin/env python3
#
# Copyright (C) 2016 James Murphy
# Licensed under the GPL version 2 only
#
# A battery indicator blocklet script for i3blocks

from subprocess import check_output

status = check_output(['acpi'], universal_newlines=True)

if not status:
    # stands for no battery found
    # fulltext = "<span color='red'><span font='FontAwesome'>\uf00d \uf240</span></span>"
    # percentleft = 100
    # if no battery then its probably PC
    pass
else:
    state = status.split(": ")[1].split(", ")[0]
    commasplitstatus = status.split(", ")
    percentleft = int(commasplitstatus[1].split("%")[0])

    # stands for charging
    FA_LIGHTNING = "↑"

    # stands for plugged in
    FA_PLUG = "◉"

    fulltext = ""
    timeleft = ""

    def icon(percent):
        if percent < 20:
            return "▁ "
        if percent < 51:
            return "▄ "
        if percent < 70:
            return "▆ "
        if percent < 95:
            return "█ "
        return "\uf240 "

    if state == "Discharging":
        time = commasplitstatus[-1].split()[0]
        time = ":".join(time.split(":")[0:2])
        timeleft = " ({})".format(time)
        fulltext = "{} ".format(icon(percentleft))
    elif state == "Full":
        fulltext = FA_PLUG + " "
    elif state == "Unknown":
        fulltext = "   "
    else:
        fulltext = FA_LIGHTNING + " " + FA_PLUG + " "

    form = '{}%'
    fulltext += form.format(percentleft)
    fulltext += timeleft

print(fulltext)

# return with imortant code
# if percentleft < 10:
#     exit(33)
