#!/bin/sh
# REQUIRES FONT-AWESOME PACKAGE TO WORK PROPERLY

dte(){
        dte="$(date +"%D  %R")"
        echo "$dte"
}

hdd(){
        hdd="$(df -h /home | grep dev | awk '{print$3, " "  $5}')"
        echo "  $hdd"
}

mem(){
        mem="$(free -h | awk '/Mem:/ {printf $3 " / " $2}')"
        echo "  $mem"
}

upgrades(){
        upgrades="$(pacman -Qu | wc -l)"
        echo "  $upgrades"
}

vol(){
	vol="$(amixer -D pulse get Master | awk -F'[][]' 'END{print $4":"$2}')"
	echo "  $vol"
}

bat() {
	battery="$(bar-battery)"
	echo "$battery"
}

keyb() {
	keyb="$(xkblayout-state print " %s")"
	echo "$keyb"
}


status(){
	echo "$(keyb)   $(upgrades)   $(hdd)   $(vol)    $(bat)    $(dte)   "
	# echo "$(keyb)   $(mem)   $(upgrades)   $(hdd)   $(vol)    $(bat)    $(dte)   "
}


while true; do
	xsetroot -name "$(status)"
	sleep 5s
done
