#!/bin/sh
# REQUIRES FONT-AWESOME PACKAGE TO WORK PROPERLY

dte(){
        dte="$(date +"%a, %b %d %R")"
        echo "$dte"
}

hdd(){
        hdd="$(df -h /home | grep dev | awk '{print$3, " "  $5}')"
        echo "  $hdd"
}

mem(){
        mem="$(free -h | awk '/Mem:/ {printf $3 " / " $2}')"
        echo "  $mem"
}

cpu() {
    read cpu a b c previdle rest < /proc/stat
      prevtotal=$((a+b+c+previdle))
        sleep 0.5
          read cpu a b c idle rest < /proc/stat
            total=$((a+b+c+idle))
              cpu=$((100*( (total-prevtotal) - (idle-previdle) ) / (total-prevtotal) ))
                echo "  $cpu% "
}

upgrades(){
        upgrades="$(yay -Qu | wc -l)"
        echo "  $upgrades"
}

vol(){
	vol="$(amixer -D pulse get Master | awk -F'[][]' 'END{print $4":"$2}')"
	echo "  $vol"
}

bat() {
	battery="$(cat /sys/class/power_supply/BAT0/capacity)"
	echo " $battery %"
}

batstat() {
	bstat="$(cat /sys/class/power_supply/BAT0/status)"
	echo "$bstat"
}

status(){
	echo "$(mem) | $(upgrades) | $(hdd) | $(vol) | $(bat) | $(dte)"
}


while true; do
	xsetroot -name "$(status)"
	sleep 5s 
done
