#!/bin/bash

choice=$(echo -e "Lock\nSuspend\nShutdown\nLogout\nRestart\nRestart DWM" | dmenu -i -l 20 -p "Select action:")

case "$choice" in
	Lock) pixellock ;;
	Suspend) pixellock && systemctl suspend ;;
	Shutdown) shutdown now ;;
	Logout) killall xinit ;;
	Restart) reboot ;;
	"Restart DWM") pkill dwm ;;
esac
